// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


function drawCircle(color, radius, _) {
  console.log(color);
  if (radius) {
    console.log(radius[0]);
    return /* () */0;
  } else {
    console.log(1);
    return /* () */0;
  }
}

var color = 1;

exports.drawCircle = drawCircle;
exports.color      = color;
/* No side effect */
